apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kalypso-infra
  namespace: argocd
spec:
  description: Kalypso Infrastructure - LGTM + Pyroscope + Istio + MinIO
  
  sourceRepos:
    - '*'
  
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
