apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
  namespace: applications
spec:
  exporter:
    endpoint: http://kalypso-otel-collector.otel-system.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    image: sky5367/otel-autoinstrumentation-python-pyroscope:0.60b0-pyroscope2
    env:
      - name: PYROSCOPE_SERVER_ADDRESS
        value: "http://pyroscope-distributor.pyroscope.svc.cluster.local:4040"
